Repository KB-team3/AlgoGGang, pull requests merged in 2023-06, with the labels that each got.

#29 [week6] B2579_계단오르기, B1780_종이의개수
  윤상우/Week_6/B1780_종이의개수.java
  윤상우/Week_6/B2579_계단오르기.java
Labels: 상우, week6

#28 [week6] B2579_계단오르기, B1780_종이의개수
  .vscode/settings.json
  곽승규/Week_6/B1780_종이의개수.py
  곽승규/Week_6/B2579_계단오르기.py
  곽승규/Week_6/input.txt
  곽승규/Week_6/tempCodeRunnerFile.py
Labels: week6, 승규

#27 [week6] B2579_계단오르기, B1780_종이의개수
  서지수/Week_6/B1780_종이의 개수.py
  서지수/Week_6/B2579_계단 오르기.py
Labels: 지수, week6

#26 [week6] B2579_계단오르기, B1780_종이의개수
  신선영/Week_6/B1780_종이의개수.py
  신선영/Week_6/B2579_계단오르기.java
Labels: 선영, week6

#25 [week6] B2579_계단오르기, B1780_종이의개수
  길민지/Week_6/B1780_종이의개수.java
  길민지/Week_6/B2579_계단오르기.java
Labels: 민지, week6

#37 [Week7] B17281_야구, B1932_정수삼각형, P42577_전화번호목록
  서지수/Week_7/B17281_야구.py
  서지수/Week_7/B1932_정수 삼각형.py
  서지수/Week_7/P42577_전화번호목록.py
Labels: 지수, week7

#31 [week7] B17281_야구, B1932_정수삼각형, P42577_전화번호목록
  윤상우/Week_7/B17281_야구.java
  윤상우/Week_7/B1932_정수삼각형.java
  윤상우/Week_7/P42577_전화번호목록.java
Labels: 상우, week7

#36 [Week7] B17281_야구, B1932_정수 삼각형, B42577_전화번호 목록
  김태선/Week_7/B17281_야구.py
  김태선/Week_7/B1932_정수삼각형.py
  김태선/Week_7/P42557_전화번호.py
Labels: week7, 태선

#35 [Week7]B17281_야구, B1932_정수삼각형, P_전화번호목록
  .project
  이우엽/Week_6/B1780_종이의개수__ver2.java
  이우엽/Week_7/B17281_야구.java
  이우엽/Week_7/B1932_정수삼각형.java
  이우엽/Week_7/P_전화번호목록.java
Labels: 우엽, week7

#40 [Week8] B2293_동전1, B2564_경비원, B9081_단어맞추기
  윤상우/Week_8/B2293_동전1.java
  윤상우/Week_8/B2564_경비원.java
  윤상우/Week_8/B9081_단어맞추기.java
Labels: 상우, Week8

#42 [Week8] B2293_동전1, B2564_경비원, B9081_단어맞추기
  길민지/Week_8/B2293_동전1.java
  길민지/Week_8/B2564_경비원.java
  길민지/Week_8/B9081_단어맞추기.java
Labels: 민지, Week8

#38 [Week8] B2293_동전1, B2564_경비원, B9081_단어맞추기
  곽승규/Week_8/B2293_동전1.py
  곽승규/Week_8/B2564_경비원.py
  곽승규/Week_8/B9081_단어맞추기.py
Labels: 승규, Week8

#39 [Week8] B2293_동전1, B2564_경비원, B9081_단어맞추기
  신선영/Week_8/B2564_경비원.py
  신선영/Week_8/B9081_단어맞추기.py
Labels: 선영, Week8

#41 [Week8] B2293_동전1, B2564_경비원, B9081_단어맞추기
  김태선/Week_8/B2293_동전1
  김태선/Week_8/B2564_경비원
  김태선/Week_8/B9081_단어맞추기
Labels: 태선, Week8

#43 [Week8] B2293_동전1, B2564_경비원, B9081_단어맞추기
  이우엽/Week_8/B2293_동전1.java
  이우엽/Week_8/B2564_경비원.java
  이우엽/Week_8/B9081_단어맞추기.java
Labels: 우엽, Week8

#44 [Week9] P150370_개인정보수집유효기간, P159993_미로탈출, P92341_주차요금계산
  신선영/Week_9/P150370_개인정보수집유효기간.js
  신선영/Week_9/P159993_미로탈출.py
  신선영/Week_9/P92341_주차요금계산.js
Labels: 선영, week9

#47 [Week9] P150370_개인정보수집유효기간, P159993_미로탈출, P92341_주차요금계산
  곽승규/Week_9/P150370_개인정보수집유효기간.py
  곽승규/Week_9/P159993_미로탈출.py
  곽승규/Week_9/P92341_주차요금계산.py
Labels: 승규, week9

#48 [Week9] P150370_개인정보수집유효기간, P159993_미로탈출, P92341_주차요금계산
  김태선/Week_9/P150370_개인정보수집
  김태선/Week_9/P159993_미로탈출
  김태선/Week_9/P92341_주차요금계산
Labels: 태선, week9
