Repository KB-team3/AlgoGGang, pull requests merged in 2023-04, with the labels that each got.

#2 [BOJ | PYTHON] B2559_수열
  서지수/Week_1/B2559_수열.py
  서지수/Week_1/test.java
Labels: week1, 지수

#3 [ADD] 선영 1주차 코드 업로드
  신선영/Week_1/B15686_치킨배달.py
  신선영/Week_1/B2559_수열.py
  신선영/Week_1/test.java
Labels: week1, 선영

#5 [BOJ | JAVA] B2559_수열
  .DS_Store
  길민지/Week_1/B15686_치킨배달.java
  길민지/Week_1/B2559_수열.java
  길민지/Week_1/test.java
Labels: week1, 민지
