Repository KB-team3/AlgoGGang, pull requests merged in 2023-05, with the labels that each got.

#9 [week2] B16948_데스나이트, B17298_오큰수, B17626_FourSquares
  길민지/Week_2/B16948_데스나이트.java
  길민지/Week_2/B17298_오큰수.java
  길민지/Week_2/B17626_FourSquares.java
Labels: 민지, week2

#6 [week2] B16948_데스나이트, B17298_오큰수, B17626_FourSquares
  신선영/Week_2/B16948_데스나이트.py
  신선영/Week_2/B17298_오큰수.py
  신선영/Week_2/B17626_FourSquares.py
Labels: 선영, week2

#7 [week2] B16948_데스나이트, B17298_오큰수, B17626_FourSquares
  윤상우/Week_2/B16948_데스나이트.java
  윤상우/Week_2/B17298_오큰수.java
  윤상우/Week_2/B17626_FourSquares.java
Labels: 상우, week2

#10 [week2] B16948_데스나이트, B17298_오큰수, B17626_FourSquares
  서지수/Week_2/B16948_데스나이트.py
  서지수/Week_2/B17298_오큰수.py
  서지수/Week_2/B17626_FourSquares.py
Labels: 지수, week2

#8 [week2] B17298_오큰수, B17626_FourSquares, B16948_데스나이트
  이우엽/Week_2/B17298_오큰수.java
Labels: 우엽, week2

#11 [week3] B11052_카드구매하기, B1941_소문난칠공주, B15565_귀여운라이언
  이우엽/Week_3/B11052_카드구매하기.java
  이우엽/Week_3/B15565_귀여운라이언.java
  이우엽/Week_3/B1941_소문난칠공주.java
Labels: 우엽, week3

#12 [week3] B11052_카드구매하기, B1941_소문난칠공주, B15565_귀여운라이언
  신선영/Week_3/B11052_카드구매하기.py
  신선영/Week_3/B15565_귀여운라이언.py
  신선영/Week_3/B1941_소문난칠공주.py
Labels: 선영, week3

#13 [week3] B11052_카드구매하기, B1941_소문난칠공주, B15565_귀여운라이언
  윤상우/Week_3/B11052_카드구매하기.java
  윤상우/Week_3/B15565_귀여운라이언.java
  윤상우/Week_3/B1941_소문난칠공주.java
Labels: 상우, week3

#14 [week3] B11052_카드구매하기, B1941_소문난칠공주, B15565_귀여운라이언
  서지수/Week_3/B11052_카드구매하기.py
  서지수/Week_3/B15565_귀여운라이언.py
  서지수/Week_3/B1941_소문난칠공주.py
Labels: 지수, week3

#15 [week3] B11052_카드구매하기, B1941_소문난칠공주, B15565_귀여운라이언
  길민지/Week_3/B11052_카드구매하기.java
  길민지/Week_3/B15565_귀여운라이언.java
  길민지/Week_3/B1941_소문난칠공주.java
Labels: 민지, week3

#16 [week4] B13549_숨바꼭질3, B14501_퇴사, (미해결)P42895_N으로표현
  신선영/Week_4/B13549_숨바꼭질3.py
  신선영/Week_4/B14501_퇴사.py
  신선영/Week_4/[미해결]P42895_N으로표현.py
Labels: 선영, week4

#17 [week4] B13549_숨바꼭질3, B14501_퇴사, (미해결)P42895_N으로표현
  윤상우/Week_4/B13549_숨바꼭질3.java
  윤상우/Week_4/B14501_퇴사.java
  윤상우/Week_4/P42895_N으로표현.java
Labels: 상우, week4

#18 [week4] B13549_숨바꼭질3, B14501_퇴사, P42895_N으로표현
  길민지/Week_4/B13549_숨바꼭질3.java
  길민지/Week_4/B14501_퇴사.java
  길민지/Week_4/P42895_N으로표현.java
Labels: 민지, week4

#21 [week5] B21608_상어초등학교, P42840_모의고사
  길민지/Week_5/B21608_상어초등학교
  길민지/Week_5/P42840_모의고사
Labels: 민지, week5

#23 [week5] B21608_상어초등학교, P42840_모의고사
  윤상우/Week_5/B21608_상어초등학교.java
  윤상우/Week_5/P42840_모의고사.java
Labels: 상우, week5

#20 [week5] B21608_상어초등학교, P42840_모의고사
  신선영/Week_5/B21608_상어초등학교.py
  신선영/Week_5/P42840_모의고사.py
Labels: 선영, week5
