Repository KB-team3/AlgoGGang, pull requests merged in 2023-10, with the labels that each got.

#116 [Week21] P12987_숫자게임, P87846_피로도, B1753_최단경로
  신선영/Week_21/B1753_최단경로.py
  신선영/Week_21/P12987_숫자게임.py
  신선영/Week_21/P87946_피로도.py
Labels: 선영, Week21

#115 [Week21] P12987_숫자게임, P87846_피로도, B1753_최단경로
  곽승규/Week_21/B1753_최단경로.py
  곽승규/Week_21/P12987_숫자게임.py
  곽승규/Week_21/P87946_피로도.py
Labels: 승규, Week21

#118 [Week21] P12987_숫자게임, P87846_피로도, B1753_최단경로
  길민지/Week_21/B1753_최단경로.py
  길민지/Week_21/P12987_숫자게임.py
  길민지/Week_21/P87946_피로도.py
Labels: 민지, Week21

#119 [Week22] P49189_가장 먼 노드, P43162_네트워크, B14503_로봇청소기
  윤상우/Week_22/B14503_로봇청소기
  윤상우/Week_22/P43162_네트워크
  윤상우/Week_22/P49189_가장 먼 노드
Labels: 상우, week22

#120 [Week22] P49189_가장 먼 노드, P43162_네트워크, B14503_로봇청소기
  곽승규/Week_22/B14503_로봇청소기.py
  곽승규/Week_22/P43162_네트워크.py
  곽승규/Week_22/P49189_가장먼노드.py
Labels: 승규, week22

#121 [Week22] P49189_가장 먼 노드, P43162_네트워크, B14503_로봇청소기
  길민지/Week_22/B14503_로봇청소기.py
  길민지/Week_22/P43162_네트워크.py
  길민지/Week_22/P49189_가장먼노드.py
Labels: 민지, week22

#125 [Week23] B15683_감시, B1976_여행가자, P42584_주식 가격
  길민지/Week_23/B15683_감시.py
  길민지/Week_23/P1976_여행가자.py
  길민지/Week_23/P42584_주식가격.py
Labels: 민지, week23

#122 [Week23] B15683_감시, B1976_여행가자, P42584_주식 가격
  윤상우/Week_23/B15683_감시.py
  윤상우/Week_23/B1976_여행가자.py
  윤상우/Week_23/P42584_주식가격
Labels: 상우, week23

#124 [Week23] B15683_감시, B1976_여행가자, P42584_주식 가격
  신선영/Week_23/B1976_여행가자.py
  신선영/Week_23/P42584_주식가격.py
Labels: 선영, week23

#128 [Week24] B2239_스도쿠, B2225_합분해, P72412_순위검색
  길민지/Week_24/B2225_합분해.py
  길민지/Week_24/B2239_스도쿠.py
  길민지/Week_24/P72412_순위검색.py
Labels: 민지, week24

#127 [Week24] B2239_스도쿠, B2225_합분해, P72412_순위검색
  신선영/Week_24/B2239_스도쿠.py
  신선영/Week_24/P72412_순위검색.py
Labels: 선영, week24

#126 [Week24] B2239_스도쿠, B2225_합분해, P72412_순위검색
  윤상우/Week_24/B2225_합분해
  윤상우/Week_24/B2239_스도쿠
  윤상우/Week_24/P72412_순위검색
Labels: 상우, week24
