Repository KB-team3/AlgoGGang, pull requests merged in 2023-08, with the labels that each got.

#80 [Week_14] P43164_여행경로, P43238_입국심사, P84512_모음사전
  신선영/Week_14/P43164_여행경로.py
  신선영/Week_14/P43238_입국심사.java
  신선영/Week_14/P84512_모음사전.py
Labels: 선영, week14

#84 [Week_14] P43164_여행경로, P43238_입국심사, P84512_모음사전
  윤상우/Week_14/P43164_여행경로.py
  윤상우/Week_14/P43238_입국심사.py
  윤상우/Week_14/P84512_모음사전.py
Labels: 상우, week14

#85 [Week_14] P43164_여행경로, P43238_입국심사, P84512_모음사전
  서지수/Week_14/P43164_여행경로.py
  서지수/Week_14/P43238_입국심사.py
  서지수/Week_14/P84512_모음사전.py
Labels: 지수, week14

#83 [Week_14] P43164_여행경로, P43238_입국심사, P84512_모음사전
  곽승규/Week_14/P43164_여행경로.py
  곽승규/Week_14/P43238_입국심사.py
Labels: 승규, week14

#82 [Week_14] P43164_여행경로, P43238_입국심사, P84512_모음사전
  김태선/Week_14/P43164_여행경로.py
  김태선/Week_14/P43238_입국심사.py
  김태선/Week_14/P84512_모음사전.py
Labels: 태선, week14

#88 [Week_15] P17683_방금 그 곡, P77484_로또의 최고순위와 최저순위, P43165_타겟넘버
  신선영/Week_15/P17683_방금그곡.py
  신선영/Week_15/P43165_타겟넘버.java
  신선영/Week_15/P77484_로또의최고순위와최저순위.py
Labels: 선영, week15

#86 [Week_15] P17683_방금 그 곡, P77484_로또의 최고순위와 최저순위, P43165_타겟넘버
  길민지/Week_15/P17683_방금그곡.py
  길민지/Week_15/P43165_타겟넘버.py
  길민지/Week_15/P77484_로또의최고순위와최저순위.py
Labels: 민지, week15

#89 [Week_15] P17683_방금 그 곡, P77484_로또의 최고순위와 최저순위, P43165_타겟넘버
  김태선/Week_15/P17683_방금그곡.py
  김태선/Week_15/P43165_타겟넘버.py
  김태선/Week_15/P77484_로또의최고순위와최저순위.py
Labels: 태선, week15

#90 [Week_15] P17683_방금 그 곡, P77484_로또의 최고순위와 최저순위, P43165_타겟넘버
  서지수/Week_15/P17683_방금그곡.py
  서지수/Week_15/P43165_타겟넘버.py
  서지수/Week_15/P77484_로또최고순위와최저순위.py
Labels: 지수, week15

#91 [week_15] P17683_방금그곡, P77484_로또의최고와최저, P43165_타겟넘버
  이우엽/Week_14/P43164_여행경로.py
  이우엽/Week_15/P17683_방금그곡.py
  이우엽/Week_15/P43165_타겟넘버.java
  이우엽/Week_15/P77484_로또의최고와최저.java
Labels: 우엽, week15

#96 [week16] P152996_시소짝꿍, L15_3Sum, B2156_포도주 시식
  신선영/Week_16/B2156_포도주시식.py
  신선영/Week_16/L15_3sum.py
  신선영/Week_16/P152296_시소짝꿍.py
Labels: 선영, week16

#94 [week16] P152996_시소짝꿍, L15_3Sum, B2156_포도주 시식
  윤상우/Week_16/B2156_포도주시식
  윤상우/Week_16/L15_3Sum
  윤상우/Week_16/P152996_시소짝꿍
Labels: 상우, week16

#93 [week16] P152996_시소짝꿍, L15_3Sum, B2156_포도주 시식
  길민지/Week_16/B2156_포도주시식.py
  길민지/Week_16/L15_3Sum.py
  길민지/Week_16/P152996_시소짝꿍.py
Labels: 민지, week16

#97 [ADD] P152996_시소짝꿍, B2156_포도주 시식
  서지수/Week_16/B2156_포도주시식.py
  서지수/Week_16/L15.py
  서지수/Week_16/P152996_시소짝꿍.py
Labels: 지수, week16

#92 [week16] P152996_시소짝꿍, L15_3Sum, B2156_포도주 시식
  곽승규/Week_16/B2156_포도주시식.py
  곽승규/Week_16/L15_3Sum.py
  곽승규/Week_16/P152996_시소짝꿍.py
  곽승규/Week_17/B9465_스티커.py
  곽승규/Week_17/P154540_무인도여행.py
  곽승규/Week_17/P17677_뉴스클러스터링.py
Labels: 승규, week16

#98 [Week_16] P152996_시소짝꿍, B2156_포도주 시식, L15_3Sum
  김태선/Week_16/B2156_포도주시식.py
  김태선/Week_16/L15_3Sum.py
  김태선/Week_16/P152996_시소짝꿍.py
Labels: 태선, week16

#101 [Week_17] B9465_스티커, P17677_뉴스클러스터링, P154540_무인도여행
  신선영/Week_17/B9465_스티커.py
  신선영/Week_17/P154540_무인도여행.py
  신선영/Week_17/P17677_뉴스클러스터링.py
Labels: 선영, week17
